# Generated by Django 4.0.8 on 2023-06-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_courseoffer'),
        ('accounts', '0015_disciplina_professor_alter_user_managers_teste1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste1',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='teste1',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'is_lecturer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
