# Generated by Django 4.0.8 on 2023-06-01 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_courseoffer'),
        ('app', '0004_alter_newsandevents_id_alter_semester_id_and_more'),
        ('accounts', '0015_disciplina_professor_alter_user_managers_teste1'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste1',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.semester'),
        ),
        migrations.AlterField(
            model_name='teste1',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='teste1',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'is_lecturer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
